lab var    SEQN          "Sequence number"
lab var    DMPFSEQ       "Family sequence number"
lab var    DMPSTAT       "Examination/interview status"
lab var    DMARETHN      "Race-ethnicity"
lab var    DMARACER      "Race"
lab var    DMAETHNR      "Ethnicity"
lab var    HSSEX         "Sex"
lab var    HSDOIMO       "Date of screener: month"
lab var    HSAGEIR       "Age at interview (screener) - qty"
lab var    HSAGEU        "Age at interview (screener) - unit"
lab var    HSAITMOR      "Age in months at interview (screener)"
lab var    HSFSIZER      "Family size (persons in family)"
lab var    HSHSIZER      "Household size (persons in dwelling)"
lab var    DMPCNTYR      "County code"
lab var    DMPFIPSR      "FIPS code for State"
lab var    DMPMETRO      "Rural/urban code based on USDA code"
lab var    DMPCREGN      "Census region, weighting(Texas in south)"
lab var    DMPPIR        "Poverty Income Ratio (unimputed income)"
lab var    SDPPHASE      "Phase of NHANES III Survey"
lab var    SDPPSU6       "Total NHANES III pseudo-PSU"
lab var    SDPSTRA6      "Total NHANES III pseudo-stratum"
lab var    SDPPSU1       "Pseudo-PSU for phase 1"
lab var    SDPSTRA1      "Pseudo-stratum for phase 1"
lab var    SDPPSU2       "Pseudo-PSU for phase 2"
lab var    SDPSTRA2      "Pseudo-stratum for phase 2"
lab var    WTPFQX6       "Total interviewed sample final weight"
lab var    WTPFEX6       "Total MEC examined sample final weight"
lab var    WTPFHX6       "Total M+H examined sample final weight"
lab var    WTPFALG6      "Total allergy subsample final weight"
lab var    WTPFCNS6      "Total CNS subsample final weight"
lab var    WTPFSD6       "Total morning subsample final wgt"
lab var    WTPFMD6       "Total afternoon/eve subsample final wgt"
lab var    WTPFHSD6      "Total M+H morning subsample final wgt"
lab var    WTPFHMD6      "Total M+H afternoon subsample final wgt"
lab var    WTPFQX1       "Phase 1 interviewed sample final wgt"
lab var    WTPFEX1       "Phase 1 MEC examined sample final wgt"
lab var    WTPFHX1       "Phase 1 M+H examined sample final wgt"
lab var    WTPFALG1      "Phase 1 allergy subsample final wgt"
lab var    WTPFCNS1      "Phase 1 CNS subsample final wgt"
lab var    WTPFSD1       "Phase 1 morning sess subsample final wgt"
lab var    WTPFMD1       "Phase 1 aft/eve subsample final wgt"
lab var    WTPFHSD1      "Phase 1 morning M+H subsample final wgt"
lab var    WTPFHMD1      "Phase 1 aft/eve M+H subsample final wgt"
lab var    WTPFQX2       "Phase 2 interviewed sample final wgt"
lab var    WTPFEX2       "Phase 2 MEC examined sample final wgt"
lab var    WTPFHX2       "Phase 2 M+H examined sample final wgt"
lab var    WTPFALG2      "Phase 2 allergy subsample final wgt"
lab var    WTPFCNS2      "Phase 2 CNS subsample final wgt"
lab var    WTPFSD2       "Phase 2 morning sess subsample final wgt"
lab var    WTPFMD2       "Phase 2 aft/eve subsample final wgt"
lab var    WTPFHSD2      "Phase 2 morning M+H subsample final wgt"
lab var    WTPFHMD2      "Phase 2 aft/eve M+H subsample final wgt"
lab var    WTPQRP1       "Replicate 1 final interview weight"
lab var    WTPQRP2       "Replicate 2 final interview weight"
lab var    WTPQRP3       "Replicate 3 final interview weight"
lab var    WTPQRP4       "Replicate 4 final interview weight"
lab var    WTPQRP5       "Replicate 5 final interview weight"
lab var    WTPQRP6       "Replicate 6 final interview weight"
lab var    WTPQRP7       "Replicate 7 final interview weight"
lab var    WTPQRP8       "Replicate 8 final interview weight"
lab var    WTPQRP9       "Replicate 9 final interview weight"
lab var    WTPQRP10      "Replicate 10 final interview weight"
lab var    WTPQRP11      "Replicate 11 final interview weight"
lab var    WTPQRP12      "Replicate 12 final interview weight"
lab var    WTPQRP13      "Replicate 13 final interview weight"
lab var    WTPQRP14      "Replicate 14 final interview weight"
lab var    WTPQRP15      "Replicate 15 final interview weight"
lab var    WTPQRP16      "Replicate 16 final interview weight"
lab var    WTPQRP17      "Replicate 17 final interview weight"
lab var    WTPQRP18      "Replicate 18 final interview weight"
lab var    WTPQRP19      "Replicate 19 final interview weight"
lab var    WTPQRP20      "Replicate 20 final interview weight"
lab var    WTPQRP21      "Replicate 21 final interview weight"
lab var    WTPQRP22      "Replicate 22 final interview weight"
lab var    WTPQRP23      "Replicate 23 final interview weight"
lab var    WTPQRP24      "Replicate 24 final interview weight"
lab var    WTPQRP25      "Replicate 25 final interview weight"
lab var    WTPQRP26      "Replicate 26 final interview weight"
lab var    WTPQRP27      "Replicate 27 final interview weight"
lab var    WTPQRP28      "Replicate 28 final interview weight"
lab var    WTPQRP29      "Replicate 29 final interview weight"
lab var    WTPQRP30      "Replicate 30 final interview weight"
lab var    WTPQRP31      "Replicate 31 final interview weight"
lab var    WTPQRP32      "Replicate 32 final interview weight"
lab var    WTPQRP33      "Replicate 33 final interview weight"
lab var    WTPQRP34      "Replicate 34 final interview weight"
lab var    WTPQRP35      "Replicate 35 final interview weight"
lab var    WTPQRP36      "Replicate 36 final interview weight"
lab var    WTPQRP37      "Replicate 37 final interview weight"
lab var    WTPQRP38      "Replicate 38 final interview weight"
lab var    WTPQRP39      "Replicate 39 final interview weight"
lab var    WTPQRP40      "Replicate 40 final interview weight"
lab var    WTPQRP41      "Replicate 41 final interview weight"
lab var    WTPQRP42      "Replicate 42 final interview weight"
lab var    WTPQRP43      "Replicate 43 final interview weight"
lab var    WTPQRP44      "Replicate 44 final interview weight"
lab var    WTPQRP45      "Replicate 45 final interview weight"
lab var    WTPQRP46      "Replicate 46 final interview weight"
lab var    WTPQRP47      "Replicate 47 final interview weight"
lab var    WTPQRP48      "Replicate 48 final interview weight"
lab var    WTPQRP49      "Replicate 49 final interview weight"
lab var    WTPQRP50      "Replicate 50 final interview weight"
lab var    WTPQRP51      "Replicate 51 final interview weight"
lab var    WTPQRP52      "Replicate 52 final interview weight"
lab var    WTPXRP1       "Replicate 1 final exam weight"
lab var    WTPXRP2       "Replicate 2 final exam weight"
lab var    WTPXRP3       "Replicate 3 final exam weight"
lab var    WTPXRP4       "Replicate 4 final exam weight"
lab var    WTPXRP5       "Replicate 5 final exam weight"
lab var    WTPXRP6       "Replicate 6 final exam weight"
lab var    WTPXRP7       "Replicate 7 final exam weight"
lab var    WTPXRP8       "Replicate 8 final exam weight"
lab var    WTPXRP9       "Replicate 9 final exam weight"
lab var    WTPXRP10      "Replicate 10 final exam weight"
lab var    WTPXRP11      "Replicate 11 final exam weight"
lab var    WTPXRP12      "Replicate 12 final exam weight"
lab var    WTPXRP13      "Replicate 13 final exam weight"
lab var    WTPXRP14      "Replicate 14 final exam weight"
lab var    WTPXRP15      "Replicate 15 final exam weight"
lab var    WTPXRP16      "Replicate 16 final exam weight"
lab var    WTPXRP17      "Replicate 17 final exam weight"
lab var    WTPXRP18      "Replicate 18 final exam weight"
lab var    WTPXRP19      "Replicate 19 final exam weight"
lab var    WTPXRP20      "Replicate 20 final exam weight"
lab var    WTPXRP21      "Replicate 21 final exam weight"
lab var    WTPXRP22      "Replicate 22 final exam weight"
lab var    WTPXRP23      "Replicate 23 final exam weight"
lab var    WTPXRP24      "Replicate 24 final exam weight"
lab var    WTPXRP25      "Replicate 25 final exam weight"
lab var    WTPXRP26      "Replicate 26 final exam weight"
lab var    WTPXRP27      "Replicate 27 final exam weight"
lab var    WTPXRP28      "Replicate 28 final exam weight"
lab var    WTPXRP29      "Replicate 29 final exam weight"
lab var    WTPXRP30      "Replicate 30 final exam weight"
lab var    WTPXRP31      "Replicate 31 final exam weight"
lab var    WTPXRP32      "Replicate 32 final exam weight"
lab var    WTPXRP33      "Replicate 33 final exam weight"
lab var    WTPXRP34      "Replicate 34 final exam weight"
lab var    WTPXRP35      "Replicate 35 final exam weight"
lab var    WTPXRP36      "Replicate 36 final exam weight"
lab var    WTPXRP37      "Replicate 37 final exam weight"
lab var    WTPXRP38      "Replicate 38 final exam weight"
lab var    WTPXRP39      "Replicate 39 final exam weight"
lab var    WTPXRP40      "Replicate 40 final exam weight"
lab var    WTPXRP41      "Replicate 41 final exam weight"
lab var    WTPXRP42      "Replicate 42 final exam weight"
lab var    WTPXRP43      "Replicate 43 final exam weight"
lab var    WTPXRP44      "Replicate 44 final exam weight"
lab var    WTPXRP45      "Replicate 45 final exam weight"
lab var    WTPXRP46      "Replicate 46 final exam weight"
lab var    WTPXRP47      "Replicate 47 final exam weight"
lab var    WTPXRP48      "Replicate 48 final exam weight"
lab var    WTPXRP49      "Replicate 49 final exam weight"
lab var    WTPXRP50      "Replicate 50 final exam weight"
lab var    WTPXRP51      "Replicate 51 final exam weight"
lab var    WTPXRP52      "Replicate 52 final exam weight"
lab var    HYAITMO       "Age in months at youth interview"
lab var    MXPLANG       "Language used by SP in MEC"
lab var    MXPSESSR      "Session for MEC examination"
lab var    MXPTIMO       "Date of MEC exam time in: month"
lab var    MXPTIDW       "Day of week of MEC exam"
lab var    MXPAXTMR      "Age in months at MEC exam"
lab var    HXPSESSR      "Session for home examination"
lab var    HXPTIMO       "Date of home exam: month"
lab var    HXPTIDW       "Day of week of home exam"
lab var    HXPAXTMR      "Age in months at home exam"
lab var    HFVERS        "Version of household family quex"
lab var    HFINTVR       "Family interviewer number"
lab var    HFLANG        "Language of family interview"
lab var    HFA6XCR       "State or foreign country of birth"
lab var    HFA8R         "Highest grade or yr of school completed"
lab var    HFA12         "Marital status"
lab var    HFA13         "Military service"
lab var    HFB1          "Any SP covered by Medicare in last month"
lab var    HFB2          "Covered by Medicare in last month"
lab var    HFB3          "Type of Medicare coverage"
lab var    HFB4          "Covered by Medicare last mo for hospital"
lab var    HFB5          "Covered by Medicare last mo for doctor"
lab var    HFB6          "Any SP covered by Medicaid in last month"
lab var    HFB7          "Covered by Medicaid in last month"
lab var    HFB8          "Any SP covered by CHAMPUS, etc, last mo"
lab var    HFB9          "Covered by CHAMPUS/VA/military last mo"
lab var    HFB10         "Any SP cov by other health insur last mo"
lab var    HFB11         "Covered by other health insur last month"
lab var    HFB11A        "Any plan cover any hospital expenses"
lab var    HFB11B        "Any plan cover routine doctor's care"
lab var    HFB11C        "Any plan cover dental care (phase 2)"
lab var    HFB11D        "Any plan from employer or union (phase2)"
lab var    HFB11E        "Covered plan pays for operations (ph 1)"
lab var    HFB12         "Refused/limited insur, poor health (ph2)"
lab var    HFB13         "Insurance coverage check item"
lab var    HFB14AB       "No insurance: unemployed or related(ph1)"
lab var    HFB14AC       "No insur: poor health, illness, age(ph1)"
lab var    HFB14AD       "No insurance: can't afford (phase 1)"
lab var    HFB14AE       "No insur: dissatisfied w/ previous (ph1)"
lab var    HFB14AF       "No insurance: don't believe in (phase 1)"
lab var    HFB14AG       "No insurance: healthy, no need (phase 1)"
lab var    HFB14AI       "No insurance: some other reason(phase 1)"
lab var    HFB14BA       "No insur: refused for health reason(ph2)"
lab var    HFB14BB       "No insur: not employed,can't afford(ph2)"
lab var    HFB14BC       "No insur: not employed,not continue(ph2)"
lab var    HFB14BD       "No insur: employer does not offer (ph 2)"
lab var    HFB14BE       "No insur:emplyr offers,not eligible(ph2)"
lab var    HFB14BF       "No insur:emplyr offers,can't afford(ph2)"
lab var    HFB14BG       "No insur:no believe/not get/no need(ph2)"
lab var    HFB14BH       "No insurance:some other reason (phase 2)"
lab var    HFB16A        "Main reason not covered (phase 1)"
lab var    HFB16B        "Main reason not covered (phase 2)"
lab var    HFB17         "Insurance that pays any dental (phase 1)"
lab var    HFC1          "Age 17+ years check item"
lab var    HFC2S         "Mother's weight calculated in pounds"
lab var    HFC3S         "Mother's height calculated in inches"
lab var    HFC4S         "Father's weight calculated in pounds"
lab var    HFC5S         "Father's height calculated in inches"
lab var    HFC6A         "Parent high blood pres/stroke before 50"
lab var    HFC6A1        "Which parent, high blood pres/stroke"
lab var    HFC6B         "Parent heart attack/angina before 50"
lab var    HFC6B1        "Which parent, heart attack/angina"
lab var    HFC6C         "Parent high blood cholesterol at any age"
lab var    HFC6C1        "Which parent, high blood cholesterol"
lab var    HFC6D         "Parent asthma or hay fever at any age"
lab var    HFC6D1        "Which parent, asthma or hay fever"
lab var    HFC6E         "Parent diabetes at any age"
lab var    HFC6E1        "Which parent, diabetes"
lab var    HFC7S         "How long at address calculated in weeks"
lab var    HFC8S         "How long in city/town/area calc in weeks"
lab var    HFC9          "How many times moved"
lab var    HFC10         "Country mother born"
lab var    HFC11         "Country father born"
lab var    HFD1          "Head of family check item"
lab var    HFD2          "Work at job during past 2 weeks"
lab var    HFD3          "Had job/business during last 2 weeks"
lab var    HFD4          "Looking for work or on layoff"
lab var    HFD5          "Which, looking for work or on layoff"
lab var    HFD9R         "What kind of business or industry"
lab var    HFD10R        "What kind of work was person doing"
lab var    HFD12         "Class of worker"
lab var    HFE1          "When house/structure originally built"
lab var    HFE2          "How many rooms are in this home"
lab var    HFE3          "How long family lived at address - years"
lab var    HFE4          "Is home drinking water bottled or tap"
lab var    HFE5          "What is source of your home tap water"
lab var    HFE6          "Water softening or conditioning system"
lab var    HFE7          "Do any pets live in this home"
lab var    HFE8A         "Pet lives here - a dog"
lab var    HFE8B         "Pet lives here - a cat"
lab var    HFE8C         "Pet lives here - a bird"
lab var    HFE8D         "Pet lives here - a fish"
lab var    HFE8E         "Pet lives here - other pet"
lab var    HFE9          "Was forced air heat used in past 12 mo"
lab var    HFE10         "Furnace fueled by oil, gas, elect, other"
lab var    HFE11         "Was space heater used in past 12 months"
lab var    HFE12         "Space htr fueled by elect, oil,gas,other"
lab var    HFE13         "Was wood stove used in past 12 months"
lab var    HFE14         "Was fireplace used in past 12 months"
lab var    HFE15         "Is gas stove or oven used for cooking"
lab var    HFE16         "Is exhaust fan near this stove"
lab var    HFE17         "How often is exhaust fan used"
lab var    HFE18         "Was stove/oven used to heat, past 12 mo"
lab var    HFF1          "Anyone living here smoke cigs in home"
lab var    HFF2R         "# persons who smoke cigarettes in home"
lab var    HFF3A         "Cigarettes per day person 1 smokes"
lab var    HFF3B         "Cigarettes per day person 2 smokes"
lab var    HFF3C         "Cigarettes per day person 3 smokes"
lab var    HFF3D         "Cigarettes per day person 4 smokes"
lab var    HFF3E         "Cigarettes per day person 5 smokes"
lab var    HFF3F         "Cigarettes per day person 6 smokes"
lab var    HFF4          "Do you have enough food to eat"
lab var    HFF5          "# days had no food/money in past month"
lab var    HFF6A         "Reason no food: transportation problems"
lab var    HFF6B         "Reason no food: no working appliances"
lab var    HFF6C         "Reason no food: no money/food stamps/WIC"
lab var    HFF6D         "Reason no food: other reason"
lab var    HFF7          "Cut meal size, no money/food, past month"
lab var    HFF8          "Cut child's meal size, no money, past mo"
lab var    HFF9          "Any receive benefits from WIC in last mo"
lab var    HFF10         "Any receive food stamps in last 12 month"
lab var    HFF11         "Any receive food stamps at present time"
lab var    HFF12A        "Any receive employment income,last month"
lab var    HFF12B        "Receive employment income in last month"
lab var    HFF13A        "Anyone receive SS/RR pay in last month"
lab var    HFF13B        "Receive SS/RR pay in last month"
lab var    HFF13DA       "Reason getting SS/RR (phase 1)"
lab var    HFF13DB       "Reason getting SS/RR (phase 2)"
lab var    HFF13E        "Another reason getting SS (phase 1)"
lab var    HFF14A        "Any receive SSI pay, Federal, last month"
lab var    HFF14B        "Receive SSI pay, Federal, in last month"
lab var    HFF14D        "Recv separate SSI,welfare,past 4 mo(ph1)"
lab var    HFF15A        "Any receive other pension/disabl,last mo"
lab var    HFF15B        "Receive other pension/disability,last mo"
lab var    HFF16A        "Any receive public asst/welfare, last mo"
lab var    HFF16B        "Receive public assist/welfare, last mo"
lab var    HFF16D        "Anyone receive AFDC/ADC in last month"
lab var    HFF16E        "Receive AFDC/ADC in last month"
lab var    HFF17A        "Anyone receive other income, last month"
lab var    HFF17B        "Receive other income in last month"
lab var    HFF18         "Total family 12 month income < $20,000"
lab var    HFF19R        "Total family 12 month income group (ph1)"
lab var    HFF20R        "Total family income, last mo, group(ph1)"
lab var    HFHSEQN       "Family reference person sequence number"
lab var    HFHAGER       "Family reference person age - years"
lab var    HFHSEX        "Family reference person sex"
lab var    HFHFIPCR      "Family reference person birthplace"
lab var    HFHEDUCR      "Family refer person high grade completed"
lab var    HFHEMPL       "Family refer person employed, past 2 wks"
lab var    HFHMRST       "Family reference person marital status"
lab var    HFHMLSV       "Family reference person military service"
lab var    HFRELR        "Respondent relationship to refer person"
lab var    HFAGERR       "Respondent age in years"
lab var    HAVERS        "Phase and questionnaire version"
lab var    HAINTVR       "Interviewer number"
lab var    HALANG        "Language of interview"
lab var    HAA1          "Did SP receive introductory letter"
lab var    HAA2          "Did SP hear about survey any other way"
lab var    HAA2A         "Other way heard about the survey"
lab var    HAA3          "Check Item. Refer to age of  SP"
lab var    HAA4          "What is today's date"
lab var    HAA5          "What is the day of the week"
lab var    HAA6A         "What is your complete address: street"
lab var    HAA6B         "What is your complete address: city/town"
lab var    HAA6C         "What is your complete address: state"
lab var    HAA6D         "What is your complete address: zip code"
lab var    HAB1          "Is health in general excellent,...,poor"
lab var    HAB2          "Go to particular place for health care"
lab var    HAB3          "Is there one particular doctor you see"
lab var    HAB4          "Past 12 mos, # times stayed in hospital"
lab var    HAB5          "Past 12 months, # times saw doctor"
lab var    HAB6S         "How long since saw doctor, etc - months"
lab var    HAB7          "Past 12 mos, # times in nursing home"
lab var    HAC1A         "Doctor ever told you had: arthritis"
lab var    HAC1B         "Type arthritis:rheumatoid,osteoarthritis"
lab var    HAC1C         "Doctor told: congestive heart failure"
lab var    HAC1D         "Doctor ever told you had: stroke"
lab var    HAC1E         "Doctor ever told you had: asthma"
lab var    HAC1F         "Doctor ever told had: chronic bronchitis"
lab var    HAC1G         "Doctor ever told you had: emphysema"
lab var    HAC1H         "Doctor ever told you had: hay fever"
lab var    HAC1I         "Doctor ever told you had: cataracts"
lab var    HAC1J         "Doctor ever told you had: goiter"
lab var    HAC1K         "Doctor ever told you had:thyroid disease"
lab var    HAC1L         "Doctor ever told you had: lupus"
lab var    HAC1M         "Doctor ever told you had: gout"
lab var    HAC1N         "Doctor ever told you had: skin cancer"
lab var    HAC1O         "Doctor ever told you had: other cancer"
lab var    HAC2E         "Do you still have asthma"
lab var    HAC2F         "Do you still have bronchitis"
lab var    HAC2H         "Do you still have hay fever"
lab var    HAC2J         "Do you still have goiter"
lab var    HAC2K         "Do you still have thyroid disease"
lab var    HAC3AR        "Age when first told you had arth -- yrs"
lab var    HAC3CR        "Age 1st told had cong heart fail -- yrs"
lab var    HAC3DR        "Age when 1st told you had stroke -- yrs"
lab var    HAC3ER        "Age when 1st told you had asthma -- yrs"
lab var    HAC3FR        "Age when 1st told you had bronch -- yrs"
lab var    HAC3GR        "Age when first told you had emph -- yrs"
lab var    HAC3HR        "Age when 1st told you had hay fev -- yrs"
lab var    HAC3IR        "Age when 1st told you had catar -- yrs"
lab var    HAC3JR        "Age when 1st told you had goiter -- yrs"
lab var    HAC3KR        "Age 1st told had other thyr dis -- yrs"
lab var    HAC3LR        "Age when first told you had lupus -- yrs"
lab var    HAC3MR        "Age when first told you had gout -- yrs"
lab var    HAC3NR        "Age when 1st told had skin cancer -- yrs"
lab var    HAC3OR        "Age when 1st told had other cancr -- yrs"
lab var    HAC3OS        "Where was cancer located when first told"
lab var    HAC4A         "Doctor told relatives they had diabetes"
lab var    HAC4B         "Any relatives had heart attack before 50"
lab var    HAC5A1        "Did grandmother have diabetes"
lab var    HAC5A2        "Did grandfather have diabetes"
lab var    HAC5A3        "Did mother have diabetes"
lab var    HAC5A4        "Did father have diabetes"
lab var    HAC5A5        "Did sister have diabetes"
lab var    HAC5A6        "Did brother have diabetes"
lab var    HAC5A7        "Did aunt have diabetes"
lab var    HAC5A8        "Did uncle have diabetes"
lab var    HAC5A9        "Did cousin have diabetes"
lab var    HAC5A10       "Did son have diabetes"
lab var    HAC5A11       "Did daughter have diabetes"
lab var    HAC5A12       "Did other relative have diabetes"
lab var    HAC5B1        "Did grandmother have heart attack"
lab var    HAC5B2        "Did grandfather have heart attack"
lab var    HAC5B3        "Did mother have heart attack"
lab var    HAC5B4        "Did father have heart attack"
lab var    HAC5B5        "Did sister have heart attack"
lab var    HAC5B6        "Did brother have heart attack"
lab var    HAC5B7        "Did aunt have heart attack"
lab var    HAC5B8        "Did uncle have heart attack"
lab var    HAC5B9        "Did cousin have heart attack"
lab var    HAC5B10       "Did son have heart attack"
lab var    HAC5B11       "Did daughter have heart attack"
lab var    HAC5B12       "Did other relative have heart attack"
lab var    HAC6          "Doctor told mother she had osteoporosis"
lab var    HAC7          "Did your bio mother ever fracture hip"
lab var    HAC7A         "How many times mother fractured hip"
lab var    HAC8          "Age of mother at first hip fracture"
lab var    HAD1          "Ever been told you have sugar/diabetes"
lab var    HAD2          "Check item. Refer to sex of SP"
lab var    HAD3          "Were you pregnant when told had diabetes"
lab var    HAD4          "Other than pregnant,doctor told diabetes"
lab var    HAD5R         "Age first told you had diabetes -- yrs"
lab var    HAD6          "Are you now taking insulin"
lab var    HAD7S         "How often you take insulin - times/week"
lab var    HAD8          "On average, how many units per day taken"
lab var    HAD9S         "How long have you taken insulin - months"
lab var    HAD10         "Are you now taking diabetes pills"
lab var    HAD11AS       "How often check urine for sugar-times/mo"
lab var    HAD11BS       "How often check blood for sugar-times/mo"
lab var    HAD12S        "# days since last eye exam by doctor"
lab var    HAD13S        "# days since eye exam w/ pupils dilated"
lab var    HAD14         "Ever had photographs taken of retina"
lab var    HAD15         "Ever told diabetes affected your eyes"
lab var    HAE1          "How long since doctor took blood press"
lab var    HAE2          "Doctor ever told had hypertension/HBP"
lab var    HAE3          "Told 2+ times you had hypertension/HBP"
lab var    HAE4A         "Doctor told take prescribed med for HBP"
lab var    HAE4B         "Doctor told control/lose weight for HBP"
lab var    HAE4C         "Doctor told cut salt intake for HBP"
lab var    HAE4D         "Doctor told do anything else for HBP"
lab var    HAE4D1        "Doctor told exercise more for HBP"
lab var    HAE4D2        "Doctor told restrict alcohol for HBP"
lab var    HAE4D3        "Doctor told stop smoking for HBP"
lab var    HAE4D4        "Doctor told reduce tension for HBP"
lab var    HAE4D5        "Doctor told change diet for HBP"
lab var    HAE4D6        "Doctor told make other changes for HBP"
lab var    HAE5A         "Now taking prescribed medicine for HBP"
lab var    HAE5B         "Now controlling or losing weight for HBP"
lab var    HAE5C         "Now using less salt or sodium for HBP"
lab var    HAE5D1        "Now exercising for high blood pressure"
lab var    HAE5D2        "Now restricting alcohol for HBP"
lab var    HAE5D3        "Now quit smoking for high blood pressure"
lab var    HAE5D4        "Now reduced tension for HBP"
lab var    HAE5D5        "Now made diet changes for HBP"
lab var    HAE5D6        "Now made other changes for HBP"
lab var    HAE6          "Ever had blood cholesterol checked"
lab var    HAE7          "Doctor told blood cholesterol level high"
lab var    HAE8A         "Doctor told eat less fat for HBC"
lab var    HAE8B         "Doctor told lose weight for HBC"
lab var    HAE8C         "Doctor told exercise for HBC"
lab var    HAE8D         "Doctor told take medicine for HBC"
lab var    HAE9A         "Now eat less high fat foods for HBC"
lab var    HAE9B         "Now losing weight to lower cholesterol"
lab var    HAE9C         "Now exercising to lower cholesterol"
lab var    HAE9D         "Take prescribed med to lower cholesterol"
lab var    HAE10         "Check item. Mark first applicable box"
lab var    HAE11A        "On own for HBC, eat fewer high fat foods"
lab var    HAE11B        "On own for HBC, controlled/lost weight"
lab var    HAE11C        "On own for HBC, exercise more"
lab var    HAF1          "Ever had any pain or discomfort in chest"
lab var    HAF2          "Get chest pain when walk uphill or hurry"
lab var    HAF3          "Get chest pain if walk at ordinary pace"
lab var    HAF4          "What do if get chest pain while walking"
lab var    HAF5          "If stand still is chest pain relieved"
lab var    HAF6          "How soon is the chest pain relieved"
lab var    HAF7A         "Where is pain/discomfort located -area 1"
lab var    HAF7B         "Where is pain/discomfort located -area 2"
lab var    HAF7C         "Where is pain/discomfort located -area 3"
lab var    HAF7D         "Where is pain/discomfort located -area 4"
lab var    HAF7E         "Where is pain/discomfort located -area 5"
lab var    HAF7F         "Where is pain/discomfort located -area 6"
lab var    HAF7G         "Where is pain/discomfort located -area 7"
lab var    HAF7H         "Where is pain/discomfort located -area 8"
lab var    HAF9          "Ever had severe chest pain for half hr +"
lab var    HAF10         "Doctor ever told you had a heart attack"
lab var    HAF11         "How many heart attacks have you had"
lab var    HAF12R        "Age when you had 1st heart attack -- yrs"
lab var    HAF13R        "Age when had last heart attack -- yrs"
lab var    HAF14         "Get pain in either leg while walking"
lab var    HAF15         "Leg pain begin while stand still/sitting"
lab var    HAF16         "In what part of leg do you feel it"
lab var    HAF17         "Get leg pain when walk uphill or hurry"
lab var    HAF18         "Get leg pain,walk at ordinary pace,level"
lab var    HAF19         "Leg pain ever disappear while walking"
lab var    HAF20         "If leg pain: stop walking or continue"
lab var    HAF21         "Is leg pain relieved if you stand still"
lab var    HAF22         "How soon is leg pain relieved"
lab var    HAF23         "Weak/paralysis on face,arm,leg for >5min"
lab var    HAF24         "Numbness etc,1 side face/body for >5 min"
lab var    HAF25         "Loss of vision in 1/both eyes for >5 min"
lab var    HAF26         "Severe dizziness for more than 5 minutes"
lab var    HAF27         "Problem with ability to speak/understand"
lab var    HAG1          "Check item. Refer to age of SP"
lab var    HAG2          "Ever had back pain most days for 1+ mo"
lab var    HAG3          "Have you had back pain in past 12 months"
lab var    HAG4A         "What part of back is pain - area 1"
lab var    HAG4B         "What part of back is pain - area 2"
lab var    HAG4C         "What part of back is pain - area 3"
lab var    HAG5A         "Doctor told you had broken/fractured hip"
lab var    HAG5B         "Doctor told had broken/fractured wrist"
lab var    HAG5C         "Doctor told had broken/fractured spine"
lab var    HAG6A         "Number of times you fractured your hip"
lab var    HAG6B         "Number of times fractured your wrist"
lab var    HAG6C         "Number of times fractured your spine"
lab var    HAG7          "Check item. Refer to G5"
lab var    HAG8A         "Site of fracture 1"
lab var    HAG8B         "Site of fracture 2"
lab var    HAG8C         "Site of fracture 3"
lab var    HAG8D         "Site of fracture 4"
lab var    HAG8E         "Site of fracture 5"
lab var    HAG8F         "Site of fracture 6"
lab var    HAG9AR        "Age when fractured ...- 1st time -- yrs"
lab var    HAG9BR        "Age when fractured ...- 2nd time -- yrs"
lab var    HAG9CR        "Age when fractured ...- 3rd time -- yrs"
lab var    HAG9DR        "Age when fractured ...- 4th time -- yrs"
lab var    HAG9ER        "Age when fractured ...- 5th time -- yrs"
lab var    HAG9FR        "Age when fractured ...- 6th time -- yrs"
lab var    HAG10A        "Fracture 1: low/hi fall or severe trauma"
lab var    HAG10B        "Fracture 2: low/hi fall or severe trauma"
lab var    HAG10C        "Fracture 3: low/hi fall or severe trauma"
lab var    HAG10D        "Fracture 4: low/hi fall or severe trauma"
lab var    HAG10E        "Fracture 5: low/hi fall or severe trauma"
lab var    HAG10F        "Fracture 6: low/hi fall or severe trauma"
lab var    HAG11         "Doctor ever told you had osteoporosis"
lab var    HAG12         "Were you treated for osteoporosis"
lab var    HAG13         "Check item. Refer to age of SP"
lab var    HAG14         "# times fall on floor/object past 12 mo"
lab var    HAG15         "Fall cause broken bone, injury, med care"
lab var    HAG16         "Ever had hand pain most days for 6+ wks"
lab var    HAG17A        "Pain, stiff right hand, joint 1"
lab var    HAG17B        "Pain, stiff right hand, joint 2"
lab var    HAG17C        "Pain, stiff right hand, joint 3"
lab var    HAG17D        "Pain, stiff right hand, joint 4"
lab var    HAG17E        "Pain, stiff right hand, joint 5"
lab var    HAG17F        "Pain, stiff right hand, joint 6"
lab var    HAG17G        "Pain, stiff right hand, joint 7"
lab var    HAG17H        "Pain, stiff right hand, joint 8"
lab var    HAG17I        "Pain, stiff right hand, joint 9"
lab var    HAG17J        "Pain, stiff right hand, joint 10"
lab var    HAG17K        "Pain, stiff right hand, joint 11"
lab var    HAG17L        "Pain, stiff right hand, joint 12"
lab var    HAG17M        "Pain, stiff right hand, joint 13"
lab var    HAG17N        "Pain, stiff right hand, joint 14"
lab var    HAG17O        "Pain, stiff right hand, joint 15"
lab var    HAG17FF       "Pain, stiff right hand, joint 32"
lab var    HAG17P        "Pain, stiff left hand, joint 16"
lab var    HAG17Q        "Pain, stiff left hand, joint 17"
lab var    HAG17R        "Pain, stiff left hand, joint 18"
lab var    HAG17S        "Pain, stiff left hand, joint 19"
lab var    HAG17T        "Pain, stiff left hand, joint 20"
lab var    HAG17U        "Pain, stiff left hand, joint 21"
lab var    HAG17V        "Pain, stiff left hand, joint 22"
lab var    HAG17W        "Pain, stiff left hand, joint 23"
lab var    HAG17X        "Pain, stiff left hand, joint 24"
lab var    HAG17Y        "Pain, stiff left hand, joint 25"
lab var    HAG17Z        "Pain, stiff left hand, joint 26"
lab var    HAG17AA       "Pain, stiff left hand, joint 27"
lab var    HAG17BB       "Pain, stiff left hand, joint 28"
lab var    HAG17CC       "Pain, stiff left hand, joint 29"
lab var    HAG17DD       "Pain, stiff left hand, joint 30"
lab var    HAG17EE       "Pain, stiff left hand, joint 31"
lab var    HAG18         "Swelling in hands...most days for 6+ wks"
lab var    HAG19A        "Swelling in right hand, joint 1"
lab var    HAG19B        "Swelling in right hand, joint 2"
lab var    HAG19C        "Swelling in right hand, joint 3"
lab var    HAG19D        "Swelling in right hand, joint 4"
lab var    HAG19E        "Swelling in right hand, joint 5"
lab var    HAG19F        "Swelling in right hand, joint 6"
lab var    HAG19G        "Swelling in right hand, joint 7"
lab var    HAG19H        "Swelling in right hand, joint 8"
lab var    HAG19I        "Swelling in right hand, joint 9"
lab var    HAG19J        "Swelling in right hand, joint 10"
lab var    HAG19K        "Swelling in right hand, joint 11"
lab var    HAG19L        "Swelling in right hand, joint 12"
lab var    HAG19M        "Swelling in right hand, joint 13"
lab var    HAG19N        "Swelling in right hand, joint 14"
lab var    HAG19O        "Swelling in right hand, joint 15"
lab var    HAG19FF       "Swelling in right hand, joint 32"
lab var    HAG19P        "Swelling in left  hand, joint 16"
lab var    HAG19Q        "Swelling in left hand, joint 17"
lab var    HAG19R        "Swelling in left hand, joint 18"
lab var    HAG19S        "Swelling in left hand, joint 19"
lab var    HAG19T        "Swelling in left hand, joint 20"
lab var    HAG19U        "Swelling in left hand, joint 21"
lab var    HAG19V        "Swelling in left hand, joint 22"
lab var    HAG19W        "Swelling in left hand, joint 23"
lab var    HAG19X        "Swelling in left hand, joint 24"
lab var    HAG19Y        "Swelling in left hand, joint 25"
lab var    HAG19Z        "Swelling in left hand, joint 26"
lab var    HAG19AA       "Swelling in left hand, joint 27"
lab var    HAG19BB       "Swelling in left hand, joint 28"
lab var    HAG19CC       "Swelling in left hand, joint 29"
lab var    HAG19DD       "Swelling in left hand, joint 30"
lab var    HAG19EE       "Swelling in left hand, joint 31"
lab var    HAG20         "Stiff hands in morn most days for 6+ wks"
lab var    HAG21         "How long does morning stiffness last"
lab var    HAG22         "Ever have knee pain most days for 6+ wks"
lab var    HAG23         "Have pain in right, left, or both knees"
lab var    HAG24         "Does knee hurt at rest as well as moving"
lab var    HAG25         "Swelling in knees...most days for 6+ wks"
lab var    HAG26         "Swelling in right, left, or both knees"
lab var    HAG27         "Stiff knees in morn most days for 6+ wks"
lab var    HAG28         "Stiffness in right, left, or both knees"
lab var    HAG29         "How long morning knee stiffness last"
lab var    HAG30         "Ever had hip pain most days for 6+ weeks"
lab var    HAG31         "Have pain in right, left, or both hips"
lab var    HAG32         "Doctor ever told you had hip dysplasia"
lab var    HAG33         "Doctor ever told you had scoliosis"
lab var    HAG34         "Do you have chronic limp (lasted >3 mo)"
lab var    HAH1          "Difficulty walking a quarter of a mile"
lab var    HAH2          "Difficulty walking 10 steps without rest"
lab var    HAH3          "Difficulty stooping, crouching, kneeling"
lab var    HAH4          "Difficulty lifting or carrying 10 pounds"
lab var    HAH5          "Difficulty doing chores around the house"
lab var    HAH6          "Difficulty preparing own meals"
lab var    HAH7          "Difficulty managing your money"
lab var    HAH8          "Difficulty walking room to room, 1 level"
lab var    HAH9          "Difficulty standing from armless chair"
lab var    HAH10         "Difficulty getting in or out of bed"
lab var    HAH11         "Difficulty eating"
lab var    HAH12         "Difficulty dressing yourself"
lab var    HAH13         "Need help with personal care needs"
lab var    HAH14         "Need help in handling routine needs"
lab var    HAH15         "Use device to help get around: cane, etc"
lab var    HAH16         "Do you use any special eating utensils"
lab var    HAH17         "Use aids or devices to help you dress"
lab var    HAJ0          "Check item. Refer to age of SP"
lab var    HAJ1          "Pain in area in diagram in past 12 mo"
lab var    HAJ2A         "Most uncomfortable pain located - area 1"
lab var    HAJ2B         "Most uncomfortable pain located - area 2"
lab var    HAJ2C         "Most uncomfortable pain located - area 3"
lab var    HAJ3S         "Past 12 mo, longest episode of pain -min"
lab var    HAJ4          "How many days had pain in past 12 months"
lab var    HAJ5          "Was pain continuous or did come and go"
lab var    HAJ6          "If moved around,hurt more/less/no differ"
lab var    HAJ7          "Ever seen doctor about this pain"
lab var    HAJ8          "What did the doctor say caused the pain"
lab var    HAJ9          "Doctor ever told you had gallstones"
lab var    HAJ10         "Reason visit doctor when told gallstones"
lab var    HAJ11         "Gallstone medical treatment, not surgery"
lab var    HAJ12         "Have you ever had gallbladder surgery"
lab var    HAJ13         "Age when you had gallbladder surgery"
lab var    HAJ14         "Check item. Refer to J8, J10, and J12"
lab var    HAJ15         "Pain continue after gallbladder surgery"
lab var    HAJ16         "Doctor ever told you had gallstones"
lab var    HAJ17         "Have you ever had gallbladder surgery"
lab var    HAJ18R        "Age when had gallbladder surgery -- yrs"
lab var    HAK1          "Have you ever had kidney stones"
lab var    HAK2          "How many times you passed a kidney stone"
lab var    HAK3A         "Ever had medication for kidney stones"
lab var    HAK3A1        "Age had first kidney stone medication"
lab var    HAK3B         "Ever had lithotripsy for kidney stones"
lab var    		HAK3B1R     "Age you had first lithotripsy-recode"
lab var    HAK3C         "Ever had surgery to remove kidney stones"
lab var    		HAK3C1R     "Age 1st surgery for kidney stones-recode"
lab var    HAK4          "# times had bladder infection"
lab var    HAK5          "# of bladder infections in past 12 mos"
lab var    HAK6          "Symptoms of bladder infection for >3 mo"
lab var    HAK7          "Interstitial cystitis or painful bladder"
lab var    HAK8          "Age 1st had inter.cystitis/painful blad."
lab var    HAK9          "# times per night you get up to urinate"
lab var    HAK10         "When urinate,feel like bladder not empty"
lab var    HAK11         "Usually have trouble starting to urinate"
lab var    HAK12         "Check item. Refer to sex and age of SP"
lab var    HAK13         "Has urinary stream decreased over years"
lab var    HAK14         "Ever had non-cancer prostate surgery"
lab var    HAL1          "Cough most days, 3+ consecutive mo in yr"
lab var    HAL2          "How many years have you had this cough"
lab var    HAL3          "Bring up phlegm, 3+ consecutive mo in yr"
lab var    HAL4          "How many years had trouble with phlegm"
lab var    HAL5          "Shortness of breath, hurry/walk up hill"
lab var    HAL6          "Had wheezing,whistle in chest past 12 mo"
lab var    HAL7          "# episodes,wheezing/whistling past 12 mo"
lab var    HAL8          "# times in hospital, wheezing, past 12mo"
lab var    HAL9          "# times to doctor/ER, wheezing,past 12mo"
lab var    HAL10         "No cold but chest sounds wheezy/whistles"
lab var    HAL11A        "Stuffy, itchy, or runny nose, past 12 mo"
lab var    HAL11B        "Watery, itchy eyes in past 12 months"
lab var    HAL12         "# episodes itchy...nose/eyes, past 12 mo"
lab var    HAL13         "Check item. Refer to L6 - L11"
lab var    HAL14A        "Symptoms brought on by:exercise/cold air"
lab var    HAL14B        "Symptoms brought on by: animals"
lab var    HAL14C        "Symptoms brought on by: house dust"
lab var    HAL14D        "Symptoms brought on by: work environment"
lab var    HAL14E        "Symptoms brought on by: pollen"
lab var    HAL15A        "Month pollen symptoms worse: all months"
lab var    HAL15B        "Month pollen symptoms worse: January"
lab var    HAL15C        "Month pollen symptoms worse: February"
lab var    HAL15D        "Month pollen symptoms worse: March"
lab var    HAL15E        "Month pollen symptoms worse: April"
lab var    HAL15F        "Month pollen symptoms worse: May"
lab var    HAL15G        "Month pollen symptoms worse: June"
lab var    HAL15H        "Month pollen symptoms worse: July"
lab var    HAL15I        "Month pollen symptoms worse: August"
lab var    HAL15J        "Month pollen symptoms worse: September"
lab var    HAL15K        "Month pollen symptoms worse: October"
lab var    HAL15L        "Month pollen symptoms worse: November"
lab var    HAL15M        "Month pollen symptoms worse: December"
lab var    HAL16A        "Severe reaction from insect sting"
lab var    HAL16B        "Severe reaction < one hour after eating"
lab var    HAL17         "Severe reaction after allergy shot/test"
lab var    HAL18         "Ever give up/avoid pet due to allergies"
lab var    HAL19A        "In past 12 months had: cold or flu"
lab var    HAL19B        "In past 12 mo had: sinusitis/sinus prob"
lab var    HAL19C        "In past 12 months had: pneumonia"
lab var    HAL20A        "# episodes in past 12 month: cold or flu"
lab var    HAL20B        "# episodes in past 12 months: sinusitis"
lab var    HAL20C        "# episodes in past 12 months: pneumonia"
lab var    HAM1          "Check item. Refer to age of SP"
lab var    HAM2          "Receive meals from senior program"
lab var    HAM3          "Are senior meals delivered to your home"
lab var    HAM4          "How often do you eat breakfast"
lab var    HAM5S         "How tall are you without shoes - inches"
lab var    HAM6S         "How much do you weigh w/out clothes -lbs"
lab var    HAM7          "Check item. Refer to age of SP"
lab var    HAM8S         "How much did you weigh 10 years ago -lbs"
lab var    HAM9S         "How much did you weigh at age 25 - lbs"
lab var    HAM10S        "Up to present time,most ever weighed-lbs"
lab var    HAM11         "Consider self over/under/right weight"
lab var    HAM12         "Would you like to weigh more,less,same"
lab var    HAM13         "Tried to lose weight in past 12 months"
lab var    HAM14         "Past 12 mo, changed what eat, med reason"
lab var    HAM15A        "Medical reason to change eating: obesity"
lab var    HAM15B        "Medical reason to change eating: high BP"
lab var    HAM15C        "Med reason to change eating: cholesterol"
lab var    HAM15D        "Medical reason to change eating:diabetes"
lab var    HAM15E        "Med reason change eating: heart disease"
lab var    HAM15F        "Medical reason to change eating: allergy"
lab var    HAM15G        "Medical reason to change eating: ulcer"
lab var    HAM15H        "Med reason to change eating:other reason"
lab var    HAM15K        "Med reason to change eating: pregnancy"
lab var    HAM15L        "Med reason to change eating: arthritis"
lab var    HAM15M        "Med reason to change eating: back pain"
lab var    HAM15N        "Med reason change eating:stomach/gastric"
lab var    HAM15O        "Med reason change eating: cancer/tumors"
lab var    HAM15P        "Med reason change eat: dental/oral probs"
lab var    HAM15Q        "Med reason to change eating:constipation"
lab var    HAM15R        "Med reason change eat: gallstone/bladder"
lab var    HAM15S        "Med reason change eat: intestinal probs"
lab var    HAM15T        "Medical reason to change eating: hernia"
lab var    HAM15U        "Medical reason to change eating: anemia"
lab var    HAM15V        "Medical reason to change eating: stroke"
lab var    HAM15W        "Med reason change eating: psychological"
lab var    HAM15X        "Med to change eating:infections/viruses"
lab var    HAM15Y        "Medical reason to change eating: dietary"
lab var    HAM15Z        "Med reason to change eat: general health"
lab var    HAN1AS        "Chocolate milk and hot cocoa - times/mo"
lab var    HAN1BS        "Milk to drink or on cereal - times/month"
lab var    HAN1C         "Question 1a check item, used in skip"
lab var    HAN1D         "What type of milk - whole, 2%, 1%, skim"
lab var    HAN1ES        "Yogurt and frozen yogurt - times/month"
lab var    HAN1FS        "Ice cream,ice milk,milkshakes - times/mo"
lab var    HAN1GS        "Cheese, all types - times/month"
lab var    HAN1HS        "Pizza, calzone, lasagna - times/month"
lab var    HAN1IS        "Cheese dishes - times/month"
lab var    HAN2AS        "Stew or soup with vegetables - times/mo"
lab var    HAN2BS        "Spaghetti/pasta w/ tomato sauce-times/mo"
lab var    HAN2CS        "Bacon/sausage/processed meats - times/mo"
lab var    HAN2DS        "Liver and other organ meats - times/mo"
lab var    HAN2ES        "Beef - times/month"
lab var    HAN2FS        "Pork and ham - times/month"
lab var    HAN2GS        "Shrimp, clams, etc - times/mo"
lab var    HAN2HS        "Fish - times/month"
lab var    HAN2IS        "Chicken and turkey - times/month"
lab var    HAN2JS        "Eggs - times/month"
lab var    HAN3AS        "Orange juice, etc - times/month"
lab var    HAN3BS        "Other fruit juices - times/month"
lab var    HAN3CS        "Citrus fruits - times/month"
lab var    HAN3DS        "Melons - times/month"
lab var    HAN3ES        "Peaches, nectarines, etc - times/month"
lab var    HAN3FS        "Any other fruits - times/month"
lab var    HAN4AS        "Carrots - times/month"
lab var    HAN4BS        "Broccoli - times/month"
lab var    HAN4CS        "Brussel sprouts/cauliflower - times/mo"
lab var    HAN4DS        "White potatoes - times/month"
lab var    HAN4ES        "Sweet potatoes, yams, etc - times/month"
lab var    HAN4FS        "Tomatoes - times/month"
lab var    HAN4GS        "Spinach, greens, etc - times/month"
lab var    HAN4HS        "Tossed salad - times/month"
lab var    HAN4IS        "Cabbage, cole slaw, sauerkraut-times/mo"
lab var    HAN4JS        "Hot red chili peppers - times/month"
lab var    HAN4KS        "Other peppers - times/month"
lab var    HAN4LS        "Any other vegetables - times/month"
lab var    HAN5AS        "Beans, lentils, chickpeas - times/month"
lab var    HAN5BS        "Peanuts, peanut butter, etc - times/mo"
lab var    HAN5CS        "Cereals: All-Bran, etc - times/month"
lab var    HAN5DS        "Cereals: Total, etc - times/month"
lab var    HAN5ES        "All other cold cereals - times/month"
lab var    HAN5FS        "Cooked, hot cereals - times/month"
lab var    HAN5GS        "White bread, rolls, etc - times/month"
lab var    HAN5HS        "Dark breads and rolls - times/month"
lab var    HAN5IS        "Corn bread, muffins, tortillas-times/mo"
lab var    HAN5JS        "Flour tortillas - times/month"
lab var    HAN5KS        "Rice - times/month"
lab var    HAN5LS        "Salted snacks - times/month"
lab var    HAN6AS        "Cakes, cookies, brownies, etc - times/mo"
lab var    HAN6BS        "Chocolate candy and fudge - times/month"
lab var    HAN6CS        "Hi-C, Tang, Koolaid, etc - times/month"
lab var    HAN6DS        "Diet colas, diet sodas, etc - times/mo"
lab var    HAN6ES        "Regular colas and sodas - times/month"
lab var    HAN6FS        "Regular coffee - times/month"
lab var    HAN6GS        "Regular tea - times/month"
lab var    HAN6HS        "Beer and lite beer - times/month"
lab var    HAN6IS        "Wine, etc - times/month"
lab var    HAN6JS        "Hard liquor - times/month"
lab var    HAN7AS        "Margarine - times/month"
lab var    HAN7BS        "Butter - times/month"
lab var    HAN7CS        "Oil/vinegar, mayonnaise, etc - times/mo"
lab var    HAN8          "Have I missed any foods/bev?"
lab var    HAN8ACD       "1st other food or beverage - specified"
lab var    HAN8AS        "1st other food or beverage - times/month"
lab var    HAN8BCD       "2nd other food or beverage - specified"
lab var    HAN8BS        "2nd other food or beverage - times/month"
lab var    HAN8CCD       "3rd other food or beverage - specified"
lab var    HAN8CS        "3rd other food or beverage - times/month"
lab var    HAN8DCD       "4th other food or beverage - specified"
lab var    HAN8DS        "4th other food or beverage - times/month"
lab var    HAN8ECD       "5th other food or beverage - specified"
lab var    HAN8ES        "5th other food or beverage - times/month"
lab var    HAN8FCD       "6th other food or beverage - specified"
lab var    HAN8FS        "6th other food or beverage - times/month"
lab var    HAN9          "Check item. Refer to age of SP"
lab var    HAN10A        "How often drink milk when child (5-12)"
lab var    HAN10B        "How often drnk milk when teenager(13-17)"
lab var    HAN10C        "How often drink milk, young adult(18-35)"
lab var    HAN10D        "How often drnk milk,mid-age adult(36-65)"
lab var    HAN10E        "How often drink milk,older adult(over65)"
lab var    HAP1          "Have total blindness in one or both eyes"
lab var    HAP1A         "Total blindness in 1 eye or in both eyes"
lab var    HAP2          "Do you use glasses, contacts, or both"
lab var    HAP3          "Trouble seeing w/one/both eyes w/glasses"
lab var    HAP4          "W/glasses recognize friend across street"
lab var    HAP5          "W/ glasses recognize friend across room"
lab var    HAP6          "W/ glasses recognize friend arms length"
lab var    HAP7          "W/glasses recognize friend face,close up"
lab var    HAP8          "W/ glasses see enough to read news print"
lab var    HAP9          "W/ glasses see enough to read headlines"
lab var    HAP10         "Have total deafness in one or both ears"
lab var    HAP10A        "Total deafness in 1 ear or in both ears"
lab var    HAP11         "Do you use a hearing aid"
lab var    HAP12         "Have trouble hearing even w/hearing aid"
lab var    HAP13         "W/ aid can hear most things people say"
lab var    HAP14         "W/aid can hear only few words/loud noise"
lab var    HAP15         "Difficulty using phone, hearing problems"
lab var    HAP16         "Check item. Refer to age of SP"
lab var    HAP17A1       "Repeat item: 'apple' (first trial)"
lab var    HAP17A2       "Repeat item: 'table' (first trial)"
lab var    HAP17A3       "Repeat item: 'penny' (first trial)"
lab var    HAP17B        "Number of trials until objects learned"
lab var    HAP18A        "Dollars left: have $20 and take away $3"
lab var    HAP18B        "Dollars left: subtract $3 from $17"
lab var    HAP18C        "Dollars left: subtract $3 from $14"
lab var    HAP18D        "Dollars left: subtract $3 from $11"
lab var    HAP18E        "Dollars left: subtract $3 from $8"
lab var    HAP19A        "Repeat item: 'apple' (second trial)"
lab var    HAP19B        "Repeat item: 'table' (second trial)"
lab var    HAP19C        "Repeat item: 'penny' (second trial)"
lab var    HAQ1          "Describe natural teeth: excellent...poor"
lab var    HAQ2A         "Dental care needed:teeth filled/replaced"
lab var    HAQ2B         "Dental care needed: teeth pulled"
lab var    HAQ2C         "Dental care needed: gum treatment"
lab var    HAQ2D         "Dental care needed: denture work"
lab var    HAQ2E         "Dental care needed: relief of pain"
lab var    HAQ2F         "Dental care needed:to improve appearance"
lab var    HAQ2G         "Dental care needed: other"
lab var    HAQ2I         "Dental care needed: nothing"
lab var    HAQ2K         "Dental care needed: cleaning"
lab var    HAQ2L         "Dental care needed: checkup"
lab var    HAQ3S         "# days ago last visit dentist/hygienist"
lab var    HAQ4          "How often do you go to dentist/hygienist"
lab var    HAQ5          "Past 12 mo,had cold sores/fever blisters"
lab var    HAQ6          "Past 12 months, had canker/mouth sores"
lab var    HAQ7          "Check item. Refer to age of SP"
lab var    HAQ8          "Ever received orthodontic treatment"
lab var    HAQ9          "Age started recent orthodontic treatment"
lab var    HAR1          "Have you smoked 100+ cigarettes in life"
lab var    HAR2          "Age when you started smoking regularly"
lab var    HAR3          "Do you smoke cigarettes now"
lab var    HAR4S         "# cigarettes smoked per day"
lab var    HAR5          "How many yrs have you smoked this amount"
lab var    HAR6          "Ever period of 1+ years when smoked more"
lab var    HAR7S         "# cigarettes per day when smoking most"
lab var    HAR8          "How many years did you smoke that amount"
lab var    HAR9          "Ever quit smoking for one year or longer"
lab var    HAR10         "How many years not smoked since started"
lab var    HAR11R        "Age last smoke cigarettes reg -- yrs"
lab var    HAR12S        "# cigarettes smoked per day at that time"
lab var    HAR13         "Quit smoking,health problem from smoking"
lab var    HAR14         "Ever used chewing tabacco or snuff"
lab var    HAR15         "Age 1st use chew tobacco/snuff regularly"
lab var    HAR16         "Do you use chewing tobacco or snuff now"
lab var    HAR17         "Which - chewing tobacco or snuff"
lab var    HAR18AS       "# containers of snuff used per week"
lab var    HAR18BS       "# containers of chewing tobacco per week"
lab var    HAR19A        "Place in right, left, or front of mouth"
lab var    HAR19B        "Place in top or bottom of mouth"
lab var    HAR20R        "Age last use chew tob/snuf reg -- yrs"
lab var    HAR21         "Which used, chewing tobacco or snuff"
lab var    HAR22         "Quit chew/snuff, related health problem"
lab var    HAR23         "Ever smoke at least 20 cigars in life"
lab var    HAR24         "Do you now smoke cigars"
lab var    HAR25         "How many cigars do you smoke per day"
lab var    HAR26         "Ever smoke 20 pipes of tobacco in life"
lab var    HAR27         "Do you now smoke a pipe"
lab var    HAR28         "How many pipefuls tobacco smoke per day"
lab var    HAS1          "Past 2 wks, did you work at job/business"
lab var    HAS2          "Past 2 weeks, did you have job/business"
lab var    HAS3          "Looking for work or on layoff from job"
lab var    HAS4          "Which, looking for work or on layoff"
lab var    HAS5          "Check item.  Refer to S2"
lab var    HAS8R         "What kind of business or industry -- rcd"
lab var    HAS9R         "What kind of work were you doing -- rcd"
lab var    HAS11         "Class of worker"
lab var    HAS12S        "How long in months worked at that job"
lab var    HAS13         "Check item. Refer to S1 and S2"
lab var    HAS14         "At work, hours per day can smell smoking"
lab var    HAS15         "In job, ever wear protective equipment"
lab var    HAS16A        "Ever wear eye protection"
lab var    HAS16B        "Ever wear protective gloves"
lab var    HAS16C        "Ever wear dust mask"
lab var    HAS16D        "Ever wear respirator"
lab var    HAS17         "What kind of work were you doing longest"
lab var    HAS17R        "What kind of work doing longest  -- rcd"
lab var    HAS18         "How long this kind of work-all employers"
lab var    HAS19         "What business/industry worked in longest"
lab var    HAS19R        "Business/industry worked in longest--rcd"
lab var    HAS21         "Check item. Refer to S1 and S12"
lab var    HAS22         "What were you doing most of past 12 mo"
lab var    HAS23         "Limited in work by health problem"
lab var    HAS24         "Limited in housework by health problem"
lab var    HAS25         "Limited in activities by health problem"
lab var    HAS26         "Ever change work/housework, health prob"
lab var    HAS27A        "Did you change permanently to easier job"
lab var    HAS27B        "Did you change temporarily to easier job"
lab var    HAS27C        "Did you cut down to part-time work only"
lab var    HAS27D        "Did you have to stop work for few months"
lab var    HAS27E        "Did you retire because of a disability"
lab var    HAS27F        "Did you have to cut down on housework"
lab var    HAS27G        "Did you stop doing all housework"
lab var    HAS27H        "Did you make some other change"
lab var    HAS27HCD      "Other specify - coded"
lab var    HAS28         "Language you mainly speak at home"
lab var    HAS29         "Language you mainly speak at work/school"
lab var    HAT1S         "Past mo,how often walk mile without stop"
lab var    HAT1MET       "Walking activity - intensity rating"
lab var    HAT2          "In the past month, did you jog or run"
lab var    HAT2MET       "Jog or run activity - intensity rating"
lab var    HAT3S         "Past month, how often did you jog or run"
lab var    HAT4          "Past mo, ride bicycle/exercise bicycle"
lab var    HAT4MET       "Bicycle activity - intensity rating"
lab var    HAT5S         "Past mo, how often ride bike/exer bike"
lab var    HAT6          "In the past month did you swim"
lab var    HAT6MET       "Swim activity - intensity rating"
lab var    HAT7S         "Past month, how often did you swim"
lab var    HAT8          "Past mo, do aerobics or aerobic dancing"
lab var    HAT8MET       "Aerobics activity - intensity rating"
lab var    HAT9S         "Past mo, how often did aerobics/dancing"
lab var    HAT10         "Past month, did you do other dancing"
lab var    HAT10MET      "Other dancing activity -intensity rating"
lab var    HAT11S        "Past month, how often did other dancing"
lab var    HAT12         "Past month, do calisthenics or exercises"
lab var    HAT12MET      "Calisthenics activity - intensity rating"
lab var    HAT13S        "Past mo, how often did calisthenics/exer"
lab var    HAT14         "Past month, did you do garden/yard work"
lab var    HAT14MET      "Garden/yard activity - intensity rating"
lab var    HAT15S        "Past mo, how often did garden/yard work"
lab var    HAT16         "In the past month, did you lift weights"
lab var    HAT16MET      "Lift weights activity - intensity rating"
lab var    HAT17S        "Past mo, how often did you lift weights"
lab var    HAT18         "Past mo, any other exercises, sports ..."
lab var    HAT19CD       "PROBE: What - coded"
lab var    HAT19MET      "Other activity - intensity rating"
lab var    HAT20S        "Past mo, how often did other activity"
lab var    HAT21CD       "PROBE: Any others - coded (activity 2)"
lab var    HAT21MET      "Other activity 2 - intensity rating"
lab var    HAT22S        "Past mo, how often did other activity 2"
lab var    HAT23CD       "PROBE: Any others - coded (activity 3)"
lab var    HAT23MET      "Other activity 3 - intensity rating"
lab var    HAT24S        "Past mo, how often did other activity 3"
lab var    HAT25CD       "PROBE: Any others - Coded (activity 4)"
lab var    HAT25MET      "Other activity 4 - intensity rating"
lab var    HAT26S        "Past mo, how often did other activity 4"
lab var    HAT27         "Compare activity for past mo to past yr"
lab var    HAT28         "Active compared with men/women your age"
lab var    HAT29         "Check item. Refer to age of SP"
lab var    HAT30         "Active now compared with self 10 yrs ago"
lab var    HAV1S         "# times/week on phone w/ family, friends"
lab var    HAV2S         "How often per yr together w/friends/rels"
lab var    HAV3S         "How often per year you visit w/neighbors"
lab var    HAV4S         "How often per yr attend church/services"
lab var    HAV5          "Do you belong to any clubs or groups"
lab var    HAV6S         "How often per year attend club meetings"
lab var    HAV7R         "Weeks lived at this address -- recode"
lab var    HAV8          "How long lived in this city/town/area"
lab var    HAV9          "Have you lived anywhere longer than here"
lab var    HAV10R        "Where did you live longest -- recode"
lab var    HAV11         "How long did you live in longest place"
lab var    HAV12R        "Where were you born -- recode"
lab var    HAV13R        "If not born US, how long lived US -- yrs"
lab var    HAX1A         "Taken vitamins/minerals in past month"
lab var    HAX1B         "Taken prescriptn medicines in past month"
lab var    HAX1C         "Taken antacids in past month"
lab var    HAX2A         "How many vitamins/minerals taken"
lab var    HAX2B         "How many prescription medicines taken"
lab var    HAX2C         "How many antacids taken"
lab var    HAX3CG        "Certainty index code-1st"
lab var    HAX3DG        "Product class-1st"
lab var    HAX6SG        "How often did you take in past month-1st"
lab var    HAX8SG        "How long been taking (month)-1st"
lab var    HAX3CH        "Certainty index code-2nd"
lab var    HAX3DH        "Product class-2nd"
lab var    HAX6SH        "How often did you take in past month-2nd"
lab var    HAX8SH        "How long been taking (month)-2nd"
lab var    HAX3CI        "Certainty index code-3rd"
lab var    HAX3DI        "Product class-3rd"
lab var    HAX6SI        "How often did you take in past month-3rd"
lab var    HAX8SI        "How long been taking (month)-3rd"
lab var    HAX3CJ        "Certainty index code-4th"
lab var    HAX3DJ        "Product class-4th"
lab var    HAX6SJ        "How often did you take in past month-4th"
lab var    HAX8SJ        "How long been taking (month)-4th"
lab var    HAX3CK        "Certainty index code-5th"
lab var    HAX3DK        "Product class-5th"
lab var    HAX6SK        "How often did you take in past month-5th"
lab var    HAX8SK        "How long been taking (month)-5th"
lab var    HAX3CL        "Certainty index code-6th"
lab var    HAX3DL        "Product class-6th"
lab var    HAX6SL        "How often did you take in past month-6th"
lab var    HAX8SL        "How long been taking (month)-6th"
lab var    HAX3CM        "Certainty index code-7th"
lab var    HAX3DM        "Product class-7th"
lab var    HAX6SM        "How often did you take in past month-7th"
lab var    HAX8SM        "How long been taking (month)-7th"
lab var    HAX3CN        "Certainty index code-8th"
lab var    HAX3DN        "Product class-8th"
lab var    HAX6SN        "How often did you take in past month-8th"
lab var    HAX8SN        "How long been taking (month)-8th"
lab var    HAX3CO        "Certainty index code-9th"
lab var    HAX3DO        "Product class-9th"
lab var    HAX6SO        "How often did you take in past month-9th"
lab var    HAX8SO        "How long been taking (month)-9th"
lab var    HAX3CP        "Certainty index code-10th"
lab var    HAX3DP        "Product class-10th"
lab var    HAX6SP        "How often did you take in past mnth-10th"
lab var    HAX8SP        "How long been taking (month)-10th"
lab var    HAX3CQ        "Certainty index code-11th"
lab var    HAX3DQ        "Product class-11th"
lab var    HAX6SQ        "How often did you take in past mnth-11th"
lab var    HAX8SQ        "How long been taking (month)-11th"
lab var    HAX3CR        "Certainty index code-12th"
lab var    HAX3DR        "Product class-12th"
lab var    HAX6SR        "How often did you take in past mnth-12th"
lab var    HAX8SR        "How long been taking (month)-12th"
lab var    HAX3CS        "Certainty index code-13th"
lab var    HAX3DS        "Product class-13th"
lab var    HAX6SS        "How often did you take in past mnth-13th"
lab var    HAX8SS        "How long been taking (month)-13th"
lab var    HAX3CT        "Certainty index code-14th"
lab var    HAX3DT        "Product class-14th"
lab var    HAX6ST        "How often did you take in past mnth-14th"
lab var    HAX8ST        "How long been taking (month)-14th"
lab var    HAX3CU        "Certainty index code-15th"
lab var    HAX3DU        "Product class-15th"
lab var    HAX6SU        "How often did you take in past mnth-15th"
lab var    HAX8SU        "How long been taking (month)-15th"
lab var    HAX3CV        "Certainty index code-16th"
lab var    HAX3DV        "Product class-16th"
lab var    HAX6SV        "How often did you take in past mnth-16th"
lab var    HAX8SV        "How long been taking (month)-16th"
lab var    HAX3CW        "Certainty index code-17th"
lab var    HAX3DW        "Product class-17th"
lab var    HAX6SW        "How often did you take in past mnth-17th"
lab var    HAX8SW        "How long been taking (month)-17th"
lab var    HAX9DG        "Primary drug class code-1st"
lab var    HAX9EG        "Secondary drug class code-1st"
lab var    HAX9FG        "Tertiary drug class code-1st"
lab var    HAX11AG       "ICD-9-CM code-1st"
lab var    HAX12SG       "For how long been taking (days)-1st"
lab var    HAX9DH        "Primary drug class code-2nd"
lab var    HAX9EH        "Secondary drug class code-2nd"
lab var    HAX9FH        "Tertiary drug class code-2nd"
lab var    HAX11AH       "ICD-9-CM code-2nd"
lab var    HAX12SH       "For how long been taking (days)-2nd"
lab var    HAX9DI        "Primary drug class code-3rd"
lab var    HAX9EI        "Secondary drug class code-3rd"
lab var    HAX9FI        "Tertiary drug class code-3rd"
lab var    HAX11AI       "ICD-9-CM code-3rd"
lab var    HAX12SI       "For how long been taking (days)-3rd"
lab var    HAX9DJ        "Primary drug class code-4th"
lab var    HAX9EJ        "Secondary drug class code-4th"
lab var    HAX9FJ        "Tertiary drug class code-4th"
lab var    HAX11AJ       "ICD-9-CM code-4th"
lab var    HAX12SJ       "For how long been taking (days)-4th"
lab var    HAX9DK        "Primary drug class code-5th"
lab var    HAX9EK        "Secondary drug class code-5th"
lab var    HAX9FK        "Tertiary drug class code-5th"
lab var    HAX11AK       "ICD-9-CM code-5th"
lab var    HAX12SK       "For how long been taking (days)-5th"
lab var    HAX9DL        "Primary drug class code-6th"
lab var    HAX9EL        "Secondary drug class code-6th"
lab var    HAX9FL        "Tertiary drug class code-6th"
lab var    HAX11AL       "ICD-9-CM code-6th"
lab var    HAX12SL       "For how long been taking (days)-6th"
lab var    HAX9DM        "Primary drug class code-7th"
lab var    HAX9EM        "Secondary drug class code-7th"
lab var    HAX9FM        "Tertiary drug class code-7th"
lab var    HAX11AM       "ICD-9-CM code-7th"
lab var    HAX12SM       "For how long been taking (days)-7th"
lab var    HAX9DN        "Primary drug class code-8th"
lab var    HAX9EN        "Secondary drug class code-8th"
lab var    HAX9FN        "Tertiary drug class code-8th"
lab var    HAX11AN       "ICD-9-CM code-8th"
lab var    HAX12SN       "For how long been taking (days)-8th"
lab var    HAX9DO        "Primary drug class code-9th"
lab var    HAX9EO        "Secondary drug class code-9th"
lab var    HAX9FO        "Tertiary drug class code-9th"
lab var    HAX11AO       "ICD-9-CM code-9th"
lab var    HAX12SO       "For how long been taking (days)-9th"
lab var    HAX9DP        "Primary drug class code-10th"
lab var    HAX9EP        "Secondary drug class code-10th"
lab var    HAX9FP        "Tertiary drug class code-10th"
lab var    HAX11AP       "ICD-9-CM code-10th"
lab var    HAX12SP       "For how long been taking (days)-10th"
lab var    HAX9DQ        "Primary drug class code-11th"
lab var    HAX9EQ        "Secondary drug class code-11th"
lab var    HAX9FQ        "Tertiary drug class code-11th"
lab var    HAX11AQ       "ICD-9-CM code-11th"
lab var    HAX12SQ       "For how long been taking (days)-11th"
lab var    HAX9DR        "Primary drug class code-12th"
lab var    HAX9ER        "Secondary drug class code-12th"
lab var    HAX9FR        "Tertiary drug class code-12th"
lab var    HAX11AR       "ICD-9-CM code-12th"
lab var    HAX12SR       "For how long been taking (days)-12th"
lab var    HAX9DS        "Primary drug class code-13th"
lab var    HAX9ES        "Secondary drug class code-13th"
lab var    HAX9FS        "Tertiary drug class code-13th"
lab var    HAX11AS       "ICD-9-CM code-13th"
lab var    HAX12SS       "For how long been taking (days)-13th"
lab var    HAX9DT        "Primary drug class code-14th"
lab var    HAX9ET        "Secondary drug class code-14th"
lab var    HAX9FT        "Tertiary drug class code-14th"
lab var    HAX11AT       "ICD-9-CM code-14th"
lab var    HAX12ST       "For how long been taking (days)-14th"
lab var    HAX9DU        "Primary drug class code-15th"
lab var    HAX9EU        "Secondary drug class code-15th"
lab var    HAX9FU        "Tertiary drug class code-15th"
lab var    HAX11AU       "ICD-9-CM code-15th"
lab var    HAX12SU       "For how long been taking (days)-15th"
lab var    HAX9DV        "Primary drug class code-16th"
lab var    HAX9EV        "Secondary drug class code-16th"
lab var    HAX9FV        "Tertiary drug class code-16th"
lab var    HAX11AV       "ICD-9-CM code-16th"
lab var    HAX12SV       "For how long been taking (days)-16th"
lab var    HAX13AG       "Antacid identification code-1st"
lab var    HAX15SG       "How often did you take in past month-1st"
lab var    HAX16AG       "How much did you take ea time (quan)-1st"
lab var    		HAX16A1G    "How much did you take ea time (unit)-1st"
lab var    HAX17SG       "How long been taking (months)-1st"
lab var    HAX13AH       "Antacid identification code-2nd"
lab var    HAX15SH       "How often did you take in past month-2nd"
lab var    HAX16AH       "How much did you take ea time (quan)-2nd"
lab var    		HAX16A1H    "How much did you take ea time (unit)-2nd"
lab var    HAX17SH       "How long been taking (months)-2nd"
lab var    HAX13AI       "Antacid identification code-3rd"
lab var    HAX15SI       "How often did you take in past month-3rd"
lab var    HAX16AI       "How much did you take ea time (quan)-3rd"
lab var    		HAX16A1I    "How much did you take ea time (unit)-3rd"
lab var    HAX17SI       "How long been taking (months)-3rd"
lab var    HAX13AJ       "Antacid identification code-4th"
lab var    HAX15SJ       "How often did you take in past month-4th"
lab var    HAX16AJ       "How much did you take ea time (quan)-4th"
lab var    		HAX16A1J    "How much did you take ea time (unit)-4th"
lab var    HAX17SJ       "How long been taking (months)-4th"
lab var    HAX18A        "Taken aspirin, etc. in past month"
lab var    HAX19AS       "How often did you take in past month"
lab var    HAX18B        "Taken acetaminophen, etc. in past month"
lab var    HAX19BS       "How often did you take in past month"
lab var    HAX18C        "Taken ibuprofen, etc. in past month"
lab var    HAX19CS       "How often did you take in past month"
lab var    HAX18D        "Taken other pain rel. in past month-1st"
lab var    HAX18DB       "Other pain rel. product type-1st"
lab var    HAX19DS       "How often did you take in past month-1st"
lab var    HAX18E        "Taken other pain rel. in past month-2nd"
lab var    HAX18EB       "Other pain rel. product type-2nd"
lab var    HAX19ES       "How often did you take in past month-2nd"
lab var    HAX18F        "Taken other pain rel. in past month-3rd"
lab var    HAX18FB       "Other pain rel. product type-3rd"
lab var    HAX19FS       "How often did you take in past month-3rd"
lab var    HAX18G        "Taken other pain rel. in past month-4th"
lab var    HAX18GB       "Other pain rel. product type-4th"
lab var    HAX19GS       "How often did you take in past month-4th"
lab var    HAY6          "Main respondent for household adult quex"
lab var    HAY7          "Reason for accepting proxy respondent"
lab var    HAY8          "Was SP present during any of interview"
lab var    HAY9          "Anyone else present during interview"
lab var    HAY10         "Quality of interview"
lab var    HAY11A        "Observed SP: in bed"
lab var    HAY11B        "Observed SP: in wheelchair"
lab var    HAY11C        "Observed SP:uses cane,crutches,or walker"
lab var    HAY11D        "Observed SP: walks slowly or shuffles"
lab var    HAY11E        "Observed SP: paralysis in hands or legs"
lab var    HAY11F        "Observed SP: hearing impairment"
lab var    HAY11G        "Observe SP:speech problems(not language)"
lab var    HAY11H        "Observed SP: coughs continuously"
lab var    HAY11I        "Observed SP: dressed in street clothes"
lab var    HAY11J        "Observed SP:overweight, average, or thin"
lab var    HAZA1         "Any medical reason procedure not be done"
lab var    HAZA1A        "Med reason BP not taken(survey years4-6)"
lab var    HAZA1CC       "Med reason BP not taken - other(yrs 5-6)"
lab var    HAZA2         "Have you consumed food, etc last 30 min"
lab var    HAZA2A1       "Have you consumed food in last 30 min"
lab var    HAZA2A2       "Have you consumed alcohol in last 30 min"
lab var    HAZA2A3       "Have you consumed coffee in last 30 min"
lab var    HAZA2A4       "Have you smoked cigarettes last 30 min"
lab var    HAZA3         "Cuff size used"
lab var    HAZA4         "Arm selected"
lab var    HAZA4A        "Reason left arm selected(survey yrs 4-6)"
lab var    HAZA5         "Radial pulse (30 seconds)"
lab var    HAZA5R        "Radial pulse rate (beats/min)"
lab var    HAZA6         "Radial pulse regular/rhythmic"
lab var    HAZA7A        "First maximum inflation rate (MIL, mmHg)"
lab var    HAZA7AA       "Reason first MIL not taken (years 4-6)"
lab var    HAZA7B        "Second MIL (mm Hg) (survey years 4-6)"
lab var    HAZA7BA       "Reason second MIL not taken (years 4-6)"
lab var    HAZA8AK1      "K1 for first BP measure (systolic, mmHg)"
lab var    HAZA8AK5      "K5 for first BP measure (diastolic,mmHg)"
lab var    HAZA8A3       "Reason first BP measurement not done"
lab var    HAZA8A4       "Reason first BP measurement refused"
lab var    HAZA8BK1      "K1 for second BP measure (systolic,mmHg)"
lab var    HAZA8BK5      "K5 for second BP measure(diastolic,mmHg)"
lab var    HAZA8B3       "Reason second BP measurement not done"
lab var    HAZA8B4       "Reason second BP measurement refused"
lab var    HAZA8CK1      "K1 for third BP measure (systolic, mmHg)"
lab var    HAZA8CK5      "K5 for third BP measure (diastolic,mmHg)"
lab var    HAZA8C3       "Reason third BP measurement not done"
lab var    HAZA8C4       "Reason third BP measurement refused"
lab var    HAZA8DK1      "K1 for fourth BP (systolic,mmHg,yrs 4-6)"
lab var    HAZA8DK5      "K5 for fourth BP(diastolic,mmHg,yrs 4-6)"
lab var    HAZA8D3       "Reason fourth BP not done (years 4-6)"
lab var    HAZA8D4       "Reason fourth BP refused (years 4-6)"
lab var    HAZA9         "Reason for not taking BP (years 5-6)"
lab var    HAZA10        "Code determining BP averaging (yrs 5-6)"
lab var    HAZA11A       "Average K1 BP (survey years 5 and 6)"
lab var    HAZA11AR      "Average K1 BP after data edits"
lab var    HAZA11B       "Average K5 BP (survey years 5-6)"
lab var    HAZA11BR      "Average K5 BP after data edits"
lab var    HAZA12        "BP statement read to SP (years 5 and 6)"
lab var    HAZMNK1R      "Average K1 BP from household and MEC"
lab var    HAZNOK1R      "Number of BP's used for average K1"
lab var    HAZMNK5R      "Average K5 BP from household and MEC"
lab var    HAZNOK5R      "Number of BP's used for average K5"
